source 'https://rubygems.org'

gem 'mediawiki-gateway', github: 'MusikAnimal/mediawiki-gateway', branch: 'master'
gem 'pry-byebug', '3.3.0'
gem 'unicode', '~> 0.4.4'
gem 'mysql2', '0.5.2'
gem 'httparty', '0.16.2'
gem 'redis', '3.2.2'
gem 'i18n', '0.7.0'
gem 'nokogiri', '1.8.1'
gem 'countries', '2.1.4'
gem 'cinch', '2.3.4'
gem 'em-eventsource', path: '~/dev/em-eventsource'
