source 'https://rubygems.org'

gem 'mediawiki-gateway', github: 'MusikAnimal/mediawiki-gateway', branch: 'master'
gem 'pry-byebug', '3.3.0'
gem 'unicode', '~> 0.4.4'
gem 'mysql2', '0.4.5'
gem 'httparty', '0.13.7'
gem 'redis', '3.2.2'
gem 'i18n', '0.7.0'
gem 'nokogiri', '1.8.1'
