source 'https://rubygems.org'

gem 'mediawiki-gateway', github: 'MusikAnimal/mediawiki-gateway', branch: 'master'
gem 'pry'
gem 'unicode'
gem 'mysql2'
gem 'httparty'
gem 'redis'
gem 'i18n', '0.7.0'
gem 'nokogiri', '~> 1.13.6'
gem 'countries', '2.1.4'
gem 'cinch', '2.3.4'
gem 'em-eventsource', '0.3.1'
